use super::{ANSIKeyboardLayout, ISOKeyboardLayout, Key, KeyboardLayout};

pub fn iso() -> KeyboardLayout {
    KeyboardLayout::ISO(ISOKeyboardLayout {
        row0: [
            Key::Char('Q'),
            Key::Char('W'),
            Key::Char('E'),
            Key::Char('R'),
            Key::Char('T'),
            Key::Char('Z'),
            Key::Char('U'),
            Key::Char('I'),
            Key::Char('O'),
            Key::Char('P'),
            Key::None,
            Key::None,
        ],
        row1: [
            Key::Char('A'),
            Key::Char('S'),
            Key::Char('D'),
            Key::Char('F'),
            Key::Char('G'),
            Key::Char('H'),
            Key::Char('J'),
            Key::Char('K'),
            Key::Char('L'),
            Key::None,
            Key::None,
            Key::None,
        ],
        row2: [
            Key::None,
            Key::Char('Y'),
            Key::Char('X'),
            Key::Char('C'),
            Key::Char('V'),
            Key::Char('B'),
            Key::Char('N'),
            Key::Char('M'),
            Key::None,
            Key::None,
            Key::None,
        ],
    })
}

pub fn ansi() -> KeyboardLayout {
    KeyboardLayout::ANSI(ANSIKeyboardLayout {
        row0: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'Z',
            'U',
            'I',
            'O',
            'P',
            Key::None,
            Key::None,
            Key::None,
        ],
        row1: [
            'A',
            'S',
            'D',
            'F',
            'G',
            'H',
            'J',
            'K',
            'L',
            Key::None,
            Key::None,
        ],
        row2: [
            'Y',
            'X',
            'C',
            'V',
            'B',
            'N',
            'M',
            Key::None,
            Key::None,
            Key::None,
        ],
    })
}
