use super::{ANSIKeyboardLayout, ISOKeyboardLayout, Key};

pub fn iso() -> ISOKeyboardLayout {
    ISOKeyboardLayout {
        row0: [
            Key::Char('Q'),
            Key::Char('W'),
            Key::Char('E'),
            Key::Char('R'),
            Key::Char('T'),
            Key::Char('Y'),
            Key::Char('U'),
            Key::Char('I'),
            Key::Char('O'),
            Key::Char('P'),
            Key::None,
            Key::None,
        ],
        row1: [
            Key::Char('A'),
            Key::Char('S'),
            Key::Char('D'),
            Key::Char('F'),
            Key::Char('G'),
            Key::Char('H'),
            Key::Char('J'),
            Key::Char('K'),
            Key::Char('L'),
            Key::None,
            Key::None,
            Key::None,
        ],
        row2: [
            Key::None,
            Key::Char('Z'),
            Key::Char('X'),
            Key::Char('C'),
            Key::Char('V'),
            Key::Char('B'),
            Key::Char('N'),
            Key::Char('M'),
            Key::None,
            Key::None,
            Key::None,
        ],
    }
}

pub fn ansi() -> ANSIKeyboardLayout {
    ANSIKeyboardLayout {
        row0: [
            Key::Char('Q'),
            Key::Char('W'),
            Key::Char('E'),
            Key::Char('R'),
            Key::Char('T'),
            Key::Char('Y'),
            Key::Char('U'),
            Key::Char('I'),
            Key::Char('O'),
            Key::Char('P'),
            Key::None,
            Key::None,
            Key::None,
        ],
        row1: [
            Key::Char('A'),
            Key::Char('S'),
            Key::Char('D'),
            Key::Char('F'),
            Key::Char('G'),
            Key::Char('H'),
            Key::Char('J'),
            Key::Char('K'),
            Key::Char('L'),
            Key::None,
            Key::None,
        ],
        row2: [
            Key::Char('Z'),
            Key::Char('X'),
            Key::Char('C'),
            Key::Char('V'),
            Key::Char('B'),
            Key::Char('N'),
            Key::Char('M'),
            Key::None,
            Key::None,
            Key::None,
        ],
    }
}
